version: '3'
services:
  postgres:
    build: db
    container_name: posture-annotation-postgres
    env_file:
      - .env
    ports:
      - "5170:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
    networks:
      - posture-annotation

  pgadmin:
    image: dpage/pgadmin4:6.11
    container_name: posture-annotation-pgadmin
    volumes:
      - pgadmin:/var/lib/pgadmin
    env_file: .env
    ports:
      - "5171:80"
    depends_on:
      - postgres
    networks:
      - posture-annotation

  api:
    build:
      context: api
      dockerfile: ${BUILD_MODE}.Dockerfile
    container_name: posture-annotation-api
    env_file:
      - .env
    ports:
      - "5172:8000"
    volumes:
      - ./api/src:/app/src
      - ./api/pom.xml:/app/pom.xml
      - api-build:/app/build
      - m2:/root/.m2
    depends_on:
      - postgres
    restart: always
    tty: true
    networks:
      - posture-annotation

  client:
    build:
      context: client
      dockerfile: ${BUILD_MODE}.Dockerfile
    container_name: posture-annotation-client
    env_file:
      - .env
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - client-build:/app/build
      - node_modules:/app/node_modules
    depends_on:
      - postgres
    tty: true
    networks:
      - posture-annotation

  openapi:
    image: openapitools/openapi-generator-cli
    # build:
    #   context: openapi
    container_name: posture-annotation-openapi
    ports:
      - "5174:8080"
    volumes:
      - ./openapi:/local
      - ./client/src/lib/api/generated:/local/generated/client
      - ./api/generated:/local/generated/api
    # command: generate -i /local/openapi.yaml -g typescript-fetch -o /local/generated/client
    command: generate -i /local/openapi.yaml -g spring -o /local/generated/api --additional-properties groupId=com.generated --additional-properties artifactId=openapi-generated --additional-properties apiPackage=com.generated.api --additional-properties modelPackage=com.generated.model --additional-properties=Library=spring-boot --additional-properties interfaceOnly=true --additional-properties java17=true --additional-properties useSpringBoot3=true
    tty: true
    networks:
      - posture-annotation

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: posture-annotation-swagger-ui
    ports:
      - "5175:8080"
    environment:
      - SWAGGER_JSON=/app/openapi.yaml
    volumes:
      - ./openapi:/app
    networks:
      - posture-annotation

volumes:
  pgadmin:
  api-build:
  m2:
  client-build:
  node_modules:
  postgres:

networks:
  posture-annotation:
    driver: bridge