openapi: "3.0.3"
info:
  title: posture-annotation-api
  description: "`posture-annotation-api` is a RESTful API for the Posture Annotation project."
  version: "1.0.0"
servers:
  - url: http://api:8000
    description: Docker development server
  - url: http://localhost:5172
    description: Local development server
paths:
  /user:
    $ref: './paths/user.yaml#/user'
  /user/login:
    $ref: './paths/user.yaml#/login'
  /user/auth:
    $ref: './paths/user.yaml#/user_auth'
  /user/is_exist:
    $ref: './paths/user.yaml#/is_exist'
  /user/{id}:
    $ref: './paths/user.yaml#/user_{id}'
  /posture:
    $ref: './paths/posture.yaml#/posture'
  /posture/{id}:
    $ref: './paths/posture.yaml#/posture_{id}'
  /posture/random:
    $ref: './paths/posture.yaml#/posture_random'
  /posture/sample:
    $ref: './paths/posture.yaml#/posture_sample'
  /posture/sample/random:
    $ref: './paths/posture.yaml#/posture_sample_random'
  /posture/user/{user_id}:
    $ref: './paths/posture.yaml#/posture_user_{user_id}'
  /posture/markers:
    $ref: './paths/posture.yaml#/posture_markers'
  /posture/marker/{id}:
    $ref: './paths/posture.yaml#/posture_marker_{id}'
  /annotation:
    $ref: './paths/annotation.yaml#/annotation'
  /annotation/{id}:
    $ref: './paths/annotation.yaml#/annotation_{id}'
  /annotation/{id}/file-path:
    $ref: './paths/annotation.yaml#/annotation_{id}_file_path'
  /annotation/posture/{posture_id}:
    $ref: './paths/annotation.yaml#/annotation_posture_{posture_id}'
  /annotation/posture/{posture_id}/file-path:
    $ref: './paths/annotation.yaml#/annotation_posture_{posture_id}_file_path'
  /annotation/annotater/{annotater_id}:
    $ref: './paths/annotation.yaml#/annotation_annotater_{annotater_id}'
  /annotation/annotater/{annotater_id}/file-path:
    $ref: './paths/annotation.yaml#/annotation_annotater_{annotater_id}_file_path'
  /annotation/annotater/{annotater_id}/prod:
    $ref: './paths/annotation.yaml#/annotation_annotater_{annotater_id}_prod'
  /annotation/annotater/{annotater_id}/prod/file-path:
    $ref: './paths/annotation.yaml#/annotation_annotater_{annotater_id}_prod_file_path'
  /annotation/annotater/{annotater_id}/sample:
    $ref: './paths/annotation.yaml#/annotation_annotater_{annotater_id}_sample'
  /annotation/annotater/{annotater_id}/sample/file-path:
    $ref: './paths/annotation.yaml#/annotation_annotater_{annotater_id}_sample_file_path'
  /annotation/annotater/{annotater_id}/count:
    $ref: './paths/annotation.yaml#/annotation_annotater_{annotater_id}_count'
  /annotation/posture/{posture_id}/annotater/{annotater_id}:
    $ref: './paths/annotation.yaml#/annotation_posture_{posture_id}_annotater_{annotater_id}'
  /annotation/posture/{posture_id}/annotater/{annotater_id}/file-path:
    $ref: './paths/annotation.yaml#/annotation_posture_{posture_id}_annotater_{annotater_id}_file_path'
components:
  securitySchemes:
    bearerAuth:
      $ref: './components/securitySchemas/bearerAuth.yaml#/bearerAuth'
  schemas:
    User:
      $ref: './components/schemas/user.yaml#/User'
    UserCreate:
      $ref: './components/schemas/user.yaml#/UserCreate'
    Posture:
      $ref: './components/schemas/posture.yaml#/Posture'
    PostureUpdate:
      $ref: './components/schemas/posture.yaml#/PostureUpdate'
    PostureUpdateWithFile:
      $ref: './components/schemas/posture.yaml#/PostureUpdateWithFile'
    PostureUpdateMarkerPosition:
      $ref: './components/schemas/posture.yaml#/PostureUpdateMarkerPosition'
    Annotation:
      $ref: './components/schemas/annotation.yaml#/Annotation'
    AnnotationUpdate:
      $ref: './components/schemas/annotation.yaml#/AnnotationUpdate'
    AnnotationCreate:
      $ref: './components/schemas/annotation.yaml#/AnnotationCreate'
    AnnotationUpdateWithFile:
      $ref: './components/schemas/annotation.yaml#/AnnotationUpdateWithFile'
    AnnotationCreateWithFile:
      $ref: './components/schemas/annotation.yaml#/AnnotationCreateWithFile'
    AnnotationWithFilePath:
      $ref: './components/schemas/annotation.yaml#/AnnotationWithFilePath'
  examples:
    UserExample:
      value:
        id: 1
        name: John
        password: password
        token: token
        created_at: "2021-01-01T00:00:00Z"
        updated_at: "2024-05-01T00:00:00Z"