openapi: "3.0.3"
info:
  title: posture-annotation-api
  description: "`posture-annotation-api` is a RESTful API for the Posture Annotation project."
  version: "1.0.0"
servers:
  - url: http://api:8000
    description: Docker development server
  - url: http://localhost:5172
    description: Local development server
paths:
  /user:
    $ref: './paths/user.yaml#/user'
  /user/login:
    $ref: './paths/user.yaml#/login'
  /user/auth:
    $ref: './paths/user.yaml#/user_auth'
  /user/is_exist:
    $ref: './paths/user.yaml#/is_exist'
  /user/{id}:
    $ref: './paths/user.yaml#/user_{id}'
  /posture:
    $ref: './paths/posture.yaml#/posture'
  /posture/{id}:
    $ref: './paths/posture.yaml#/posture_{id}'
  /posture/random:
    $ref: './paths/posture.yaml#/posture_random'
  /posture/user/{user_id}:
    $ref: './paths/posture.yaml#/posture_user_{user_id}'
  /posture/annotater/{annotater_id}:
    $ref: './paths/posture.yaml#/posture_annotater_{annotater_id}'
  /posture/markers:
    $ref: './paths/posture.yaml#/posture_markers'
  /posture/marker/{id}:
    $ref: './paths/posture.yaml#/posture_marker_{id}'
components:
  securitySchemes:
    bearerAuth:
      $ref: './components/securitySchemas/bearerAuth.yaml#/bearerAuth'
  schemas:
    User:
      $ref: './components/schemas/user.yaml#/User'
    UserCreate:
      $ref: './components/schemas/user.yaml#/UserCreate'
    Posture:
      $ref: './components/schemas/posture.yaml#/Posture'
    PostureUpdate:
      $ref: './components/schemas/posture.yaml#/PostureUpdate'
    PostureUpdateWithFile:
      $ref: './components/schemas/posture.yaml#/PostureUpdateWithFile'
    PostureUpdateMarkerPosition:
      $ref: './components/schemas/posture.yaml#/PostureUpdateMarkerPosition'
  examples:
    UserExample:
      value:
        id: 1
        name: John
        password: password
        token: token
        created_at: "2021-01-01T00:00:00Z"
        updated_at: "2024-05-01T00:00:00Z"